DROP TABLE IF EXISTS MOVIE;

CREATE TABLE MOVIE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  MOVIE_NAME VARCHAR(250) NOT NULL,
  MOVIE_TITLE VARCHAR(250) NOT NULL,
  DURATION INT NOT NULL
);

DROP TABLE IF EXISTS CINEMA;

CREATE TABLE CINEMA (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CINEMA_NAME VARCHAR(250) NOT NULL,
  CINEMA_CITY VARCHAR(250) NOT NULL,
  TOTAL_SEATS INT NOT NULL
 );

DROP TABLE IF EXISTS MOVIE_SHOW;

CREATE TABLE MOVIE_SHOW (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  MOVIE_ID INT NOT NULL,
  CINEMA_ID INT NOT NULL,
  SHOW_DATE_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT FK_MOVIESHOW_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(ID),
  CONSTRAINT FK_MOVIESHOW_CINEMA FOREIGN KEY (CINEMA_ID) REFERENCES CINEMA(ID)
 );


CREATE OR REPLACE VIEW SHOW_DETAIL  AS
SELECT
 MS.ID AS SHOW_ID,  
 M.MOVIE_NAME AS MOVIE,
 C.CINEMA_NAME AS CINEMA,
 C.CINEMA_CITY AS CITY,
 MS.SHOW_DATE_TIME AS SHOW_TIME,
 M.DURATION AS DURATION
FROM 
MOVIE_SHOW AS MS, 
MOVIE AS M,
CINEMA  AS C
WHERE 
MS.MOVIE_ID = M.ID 
AND 
MS.CINEMA_ID = C.ID;


